version: "3.8"
services:
    backend:
        container_name: backend-nodejs
        build: 
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        user: "1000:1000"
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - DB_HOST=database-mysql
            - MYSQL_DATABASE=$MYSQL_DBNAME
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_PORT=$MYSQL_PORT
        depends_on:
            - database-mysql
        ports:
            - '9000:9000'
        expose:
            - 9000

    database-mysql:
        image: mysql:8.0.28-debian
        restart: unless-stopped
        # user: "1000:1000"
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_USERNAME=$MYSQL_USERNAME
            - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
        ports:
            - '3306:3306'
        expose:
            - 3306

volumes:
  dbdata: